on:
  push:
    branches:
    - main
    
jobs:
  test:
    name: testing
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: execute docker
        run: |
          docker-compose up -d
          wget http://10.5.0.5
          docker-compose stop
      - name: upload  
        uses: actions/upload-artifact@v3
        with:
          name: index
          path: index.html
          retention-days: 5
