on:
  push:
    branches:
    - main
    
jobs:
  test:
    name: testing
    runs-on: ubuntu-22.04
    steps:
      - name: execute docker
      - run: docker-compose up
      - run: wget http://10.5.0.5
        with:
          name: index
          path: index.html
          retention-days: 5
